[tool.pyright]
pythonVersion = "3.8"
typeCheckingMode = "basic"
reportImplicitStringConcatenation = "error"
reportMissingParameterType = "error"
reportUnknownArgumentType = "error" # This is for level 2, needed before reportUnknownMemberType
#reportUnknownMemberType = "error"
reportUnusedCallResult = "error"
reportGeneralTypeIssues = "error"
extraPaths = [
    "./lib/python3.8/site-packages",
    "./zato-agent/src",
    "./zato-cli/src",
    "./zato-common/src",
    "./zato-cy/src",
    "./zato-distlock/src",
    "./zato-hl7/src",
    "./zato-scheduler/src",
    "./zato-server/src",
    "./zato-sso/src",
    "./zato-testing/src",
    "./zato-web-admin/src",
    "./zato-zmq/src",
]
